FROM php:8.2-fpm

LABEL maintainer="Nick Janetakis <nick.janetakis@gmail.com>"

# Create directory
RUN mkdir /home/container

ARG UID=1000
ARG GID=1000


# RUN addgroup -G "${GID}" symfony
# RUN adduser -D -u "${UID}" -G "${GID}" symfony
# Change directory permission
# RUN adduser -D -g "${GID}" symfony
RUN useradd -u "${UID}" symfony
#RUN chown -R symfony:symfony /home/container

USER symfony
