version: "3.8"
services:
  # Mysql database container
  mysql:
    image: mysql/mysql-server:8.0
    container_name: jack_db
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - target: 3306
        published: ${MYSQL_PORT:-3306}
        protocol: tcp
    environment:
        # MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
    networks:
        - symfony

    # phpmyadmin container
    # phpmyadmin:
    #     image: phpmyadmin
    #     container_name: tutorial_phpmyadmin
    #     restart: always
    #     depends_on:
    #         - db
    #     ports:
    #         - 8080:80
    #     environment:
    #         PMA_HOST: db
    #     networks:
    #         - tutorial

    # Symfony apache project container
  php:
    build: docker/php
    container_name: jack_php
    ports:
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    depends_on:
      - mysql
    networks:
      - symfony

networks:
  symfony:

volumes:
  db_data:
