<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQnmcvgY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQnmcvgY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQnmcvgY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQnmcvgY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQnmcvgY\App_KernelDevDebugContainer([
    'container.build_hash' => 'QnmcvgY',
    'container.build_id' => '183f11d2',
    'container.build_time' => 1719491701,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQnmcvgY');
