<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO7s4CmM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO7s4CmM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerO7s4CmM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerO7s4CmM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerO7s4CmM\App_KernelDevDebugContainer([
    'container.build_hash' => 'O7s4CmM',
    'container.build_id' => '8e76996a',
    'container.build_time' => 1719818628,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO7s4CmM');
