<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXhZQQkN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXhZQQkN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXhZQQkN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXhZQQkN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXhZQQkN\App_KernelDevDebugContainer([
    'container.build_hash' => 'XhZQQkN',
    'container.build_id' => '6522a538',
    'container.build_time' => 1719653611,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXhZQQkN');
